modLoader="javafml"
loaderVersion="[32,)"
[[mods]]
modId="oldgods"
version="${file.jarVersion}"
displayName="Old Gods Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/vending-machine"
logoFile="logo.png"
authors="MacTso, Lupicus"
description='''Old Gods Mod.'''
[[dependencies.oldgods]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.oldgods]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
